### PR TITLE
Include Herwig 7.1.5

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Would be good if @qgp reviews first.

**Comment by maireiphc** [comment]
HI @mfasDa, @qgp,

  I am unsure about what to do here.
Markus did here a pull request for Herwig 7.1.5 several months ago. In the meantime, Jochen updated and pushed Herwig 7.1.5.
But it seems that in Markus version, there were some later fix about c++17.

How do you want to proceed ? We patch Jochen's version as needed with Markus later fixes ?

**Comment by mfasDa** [comment]
@maireiphc Please always consider that we need to be able to build with the o2 defaults which require c++17 - I). 

Also there is the version 7.2 now - maybe better to move directly to that tag.

**Comment by maireiphc** [comment]
Ok, I tend to agree that we may skip in the end v7.1.5, and jump directly to v7.2 from  v7.1.2 (currently built or better said, tried to be built).
See https://github.com/alisw/alidist/blob/master/herwig.sh

**Comment by maireiphc** [comment]
Ok put an "issue" as a memo for later.
https://github.com/alisw/herwig/issues/2

Closing PR here then.

**Pull request closed without merging**
